# Generated by Django 4.1.1 on 2022-09-30 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_id', models.CharField(max_length=100)),
                ('city_name', models.CharField(max_length=100)),
                ('hotel_id', models.CharField(max_length=100)),
                ('hotel_name', models.CharField(max_length=100)),
            ],
        ),
    ]
