# Generated by Django 4.1.5 on 2023-02-13 09:03

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city_id", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Highlight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon",
                    models.ImageField(
                        blank=True, null=True, upload_to="highlight_img/"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Hotel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hotel_id", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="hotel_img/"),
                ),
                ("description", models.TextField(blank=True, default="", null=True)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
                ),
                ("is_available", models.BooleanField(default=True)),
                ("terms", ckeditor.fields.RichTextField(blank=True, null=True)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test",
                        to="base.city",
                    ),
                ),
                (
                    "highlight",
                    models.ManyToManyField(related_name="hotel", to="base.highlight"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                ("image", models.ImageField(upload_to="room_img/")),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
                ),
                ("description", models.TextField()),
                ("is_available", models.BooleanField(default=True)),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("Single", "Single"),
                            ("Double", "Double"),
                            ("Family", "Family"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "id",
                    models.AutoField(
                        default=None, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room",
                        to="base.hotel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("description", models.TextField()),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review",
                        to="base.hotel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100)),
                ("address", models.CharField(max_length=100)),
                ("zipcode", models.CharField(max_length=6)),
                (
                    "country",
                    django_countries.fields.CountryField(default="NL", max_length=2),
                ),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order",
                        to="base.hotel",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room",
                        to="base.room",
                    ),
                ),
            ],
        ),
    ]
