# Generated by Django 4.1.1 on 2022-10-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('onderwerp', models.CharField(max_length=100)),
                ('bericht', models.CharField(max_length=100)),
            ],
        ),
    ]
