# Generated by Django 4.1.5 on 2023-02-08 10:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotel",
            name="terms",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
