# Generated by Django 4.1.5 on 2023-10-02 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='highlight',
            field=models.ManyToManyField(blank=True, null=True, related_name='hotel', to='base.highlight'),
        ),
    ]
