# Generated by Django 4.1.1 on 2022-12-07 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_contactform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactForm',
        ),
    ]
