# Generated by Django 4.1.5 on 2023-01-19 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_hotel_description_hotel_hotel_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='city_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='hotel_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='room_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='room_title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='hotel_image',
        ),
        migrations.AddField(
            model_name='hotel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hotel_img/'),
        ),
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
