# Generated by Django 4.1.5 on 2023-01-23 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_room_room_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='title',
        ),
    ]
