# Generated by Django 4.1.5 on 2023-01-24 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_order_address_order_country_order_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('A', 'Single'), ('B', 'Double'), ('C', 'Family')], default='A', max_length=1),
        ),
    ]
