# Generated by Django 4.1.5 on 2023-01-24 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_room_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='room', to='base.room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('Single', 'Single'), ('Double', 'Double'), ('Family', 'Family')], default='Single', max_length=50),
        ),
    ]
