# Generated by Django 4.1.5 on 2023-01-24 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_order_room_alter_room_room_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='order',
            name='room',
        ),
    ]
