# Generated by Django 4.1.5 on 2023-01-24 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_remove_order_hotel_remove_order_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='hotel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='base.hotel'),
        ),
        migrations.AddField(
            model_name='order',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='room', to='base.room'),
        ),
    ]
