# Generated by Django 4.1.5 on 2023-01-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_order_hotel_order_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('Single', 'Single'), ('Double', 'Double'), ('Family', 'Family')], max_length=50),
        ),
    ]
