# Generated by Django 4.1.5 on 2023-01-30 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_highlight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='highlight',
            name='hotel',
        ),
        migrations.AddField(
            model_name='hotel',
            name='highlight',
            field=models.ManyToManyField(related_name='hotel', to='base.highlight'),
        ),
    ]
