# Generated by Django 4.1.5 on 2023-01-30 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_remove_highlight_hotel_hotel_highlight'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlight',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='highlight_img/'),
        ),
    ]
