# Generated by Django 4.1.5 on 2023-02-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_highlight_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='token',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
