# Generated by Django 4.1.5 on 2023-02-03 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_hotel_terms_order_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='terms',
        ),
        migrations.RemoveField(
            model_name='order',
            name='created_at',
        ),
    ]
