# Generated by Django 4.1.5 on 2023-02-01 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_hotel_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='token',
        ),
        migrations.AddField(
            model_name='order',
            name='token',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
