# Generated by Django 4.1.5 on 2023-02-02 10:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_alter_order_id_alter_order_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
