# Generated by Django 4.1.5 on 2023-02-03 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_alter_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.AutoField(default=None, editable=False, primary_key=True, serialize=False),
        ),
    ]
