# Generated by Django 4.1.5 on 2023-02-06 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_order_created_at'),
        ('base', '0030_remove_order_created_at'),
        ('base', '0034_alter_room_id'),
    ]

    operations = [
    ]
