# Generated by Django 4.1.5 on 2023-02-06 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_merge_20230206_0930'),
        ('base', '0035_merge_20230206_0906'),
    ]

    operations = [
    ]
