# Generated by Django 3.2.21 on 2023-10-03 08:20

import django.core.files.storage
from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_hotel_highlight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(base_url='/static/', location=pathlib.PurePosixPath('/home/erhan/Bureaublad/maykin-booking/static')), upload_to='room_img/'),
        ),
    ]
